name: Races
main: me.Darrionat.Races.Main
description: Custom races with effects!
version: 1.1
api-version: 1.13

commands:
  race:
    aliases: [races]
    usage: /<command> [change/adminchange]
  guild:
    aliases: [guilds]
    usage: /<command>
    
permissions:
  races.*:
    description: Gives access to all Races commands
    children:
      races.command: true
      races.change: true
      races.admin: true
  races.admin:
    description: Allows a player to change any players race cost free
    default: op
  races.change:
    description: Allows a player to change their race
    default: true
  races.command:
    description: Allows a player to view their race
    default: true
  races.change:
    description: Allows a player to change their race
    default: true