#This is how often the effect of every player will be checked to see if it's active.
#Low times may create lag. Use whole seconds
EffectTimer: 15

#Forces the GUI to open to a player who joins
ForceRaceOnJoin: true

#Amount of levels it takes to change their race.
PotionResetCost: 100

messages:
    SelectType: "&eYou have selected the %type% race."
    NotPlayer: "&cOnly players have access to this command!"
    NoPermission: "&cYou do not have the permission %permission%!"
    AlreadyInGuild: "&cYou are already in a guild!"
##Guilds
Lightbringer: "&eLightbringer"
Chota: "&cChota"
Traveler: "&dTraveler"
Enforcer: "&bEnforcer"